{{- if and .Values.secret.create (not .Values.secret.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "comqtt.fullname" . }}
  labels:
    {{- include "comqtt.labels" . | nindent 4 }}
type: Opaque
{{- with .Values.secret.data }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
